version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Update Bundler Version
          command: |
            gem install bundler -v 2.0.1

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Copy Sample Database
          command: |
            cp config/database.yml.sample config/database.yml

      - run:
          name: Create Database
          command: |
            bundle exec rails db:create

      - run:
          name: Load Schema
          command: |
            bundle exec rails db:schema:load

      - run:
          name: Run Tests
          command: |
            bundle exec rspec rspec

      - store_test_results:
          path: tmp/test-results
          
      - store-artifacts:
          path: tmp/test-results
          destination: test-results

#==============================================================================#

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
